# Generated by Django 5.2.7 on 2025-10-26 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IgazolasTipus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
                ('beleszamit', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mulasztas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('ora', models.IntegerField()),
                ('tantargy', models.CharField(max_length=100)),
                ('tema', models.CharField(max_length=200)),
                ('tipus', models.CharField(max_length=50)),
                ('igazolt', models.BooleanField(default=False)),
                ('igazolas_tipusa', models.CharField(blank=True, max_length=100, null=True)),
                ('rogzites_datuma', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Osztaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagozat', models.CharField(max_length=1)),
                ('kezdes_eve', models.IntegerField()),
                ('osztalyfonokok', models.ManyToManyField(blank=True, related_name='osztalyfonokok', to=settings.AUTH_USER_MODEL)),
                ('tanulok', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Igazolas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleje', models.DateTimeField()),
                ('vege', models.DateTimeField()),
                ('megjegyzes', models.TextField(blank=True, null=True)),
                ('rogzites_datuma', models.DateField(auto_now_add=True)),
                ('megjegyzes_diak', models.TextField(blank=True, max_length=500, null=True)),
                ('diak', models.BooleanField(default=True)),
                ('ftv', models.BooleanField(default=False)),
                ('korrigalt', models.BooleanField(default=False)),
                ('diak_extra_ido_elotte', models.IntegerField(blank=True, null=True)),
                ('diak_extra_ido_utana', models.IntegerField(blank=True, null=True)),
                ('imgDriveURL', models.URLField(blank=True, max_length=300, null=True)),
                ('allapot', models.CharField(choices=[('Függőben', 'Függőben'), ('Elfogadva', 'Elfogadva'), ('Elutasítva', 'Elutasítva')], default='Függőben', max_length=50)),
                ('megjegyzes_tanar', models.TextField(blank=True, max_length=500, null=True)),
                ('kretaban_rogzitettem', models.BooleanField(default=False)),
                ('tipus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.igazolastipus')),
                ('mulasztasok', models.ManyToManyField(blank=True, to='api.mulasztas')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
    ]
