# Generated by Django 5.2.7 on 2026-10-06 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.CharField(max_length=120, verbose_name='fejlesztő')),
                ('short_description', models.CharField(max_length=160, verbose_name='rövid leírás')),
                ('logo', models.ImageField(blank=True, help_text='Négyzet alakú PNG, JPEG vagy WebP kép (SVG nem engedélyezett).', upload_to='app-logos/', verbose_name='logó')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
            ],
            options={
                'verbose_name': 'alkalmazásprofil',
                'verbose_name_plural': 'alkalmazásprofilok',
            },
        ),
    ]
