# Generated by Django 5.2.7 on 2025-10-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_igazolastipus_iskolaerdeku'),
    ]

    operations = [
        migrations.AddField(
            model_name='igazolastipus',
            name='leiras',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
