# Generated by Django 5.2.7 on 2026-10-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_applicationprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'django-csoport',
                'verbose_name_plural': 'django-csoportok',
                'db_table': 'auth_group',
                'permissions': (),
                'managed': False,
                'default_permissions': (),
                'default_related_name': 'custom_groups',
            },
        ),
        migrations.AlterModelOptions(
            name='manualgroup',
            options={'ordering': ['tree_id', 'lft'], 'verbose_name': 'csoport', 'verbose_name_plural': 'csoportok'},
        ),
    ]
