# Generated by Django 5.2.7 on 2025-10-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_igazolastipus_leiras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='igazolas',
            options={'verbose_name': 'Igazolás', 'verbose_name_plural': 'Igazolások'},
        ),
        migrations.AlterModelOptions(
            name='igazolastipus',
            options={'verbose_name': 'Igazolás Típus', 'verbose_name_plural': 'Igazolás Típusok'},
        ),
        migrations.AlterModelOptions(
            name='mulasztas',
            options={'verbose_name': 'Mulasztás', 'verbose_name_plural': 'Mulasztások'},
        ),
        migrations.AlterModelOptions(
            name='osztaly',
            options={'verbose_name': 'Osztály', 'verbose_name_plural': 'Osztályok'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profilok'},
        ),
        migrations.RemoveField(
            model_name='igazolas',
            name='megjegyzes',
        ),
    ]
