# Generated by Django 5.2.7 on 2026-10-07 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customgroup_alter_manualgroup_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
