# Generated by Django 5.2.7 on 2026-10-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_customgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationprofile',
            name='verified',
            field=models.BooleanField(default=False, help_text='Az iskola által ellenőrzött alkalmazás. Csak adminisztrátor állíthatja.', verbose_name='ellenőrzött'),
        ),
    ]
