# Generated by Django 5.2.7 on 2025-10-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_forgotpasswordtoken_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='igazolas',
            name='bkk_verification',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
