# Generated by Django 5.2.7 on 2025-10-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_igazolas_bkk_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='igazolas',
            name='ftv_hianyzas_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
