# Generated by Django 5.2.7 on 2026-10-07 00:31

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_verify_staff_applications'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
            ],
            options={
                'verbose_name': 'jogosultsági kör',
                'verbose_name_plural': 'jogosultsági körök',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='manualgroup',
            options={'ordering': ['tree_id', 'lft'], 'verbose_name': 'iskolai csoport', 'verbose_name_plural': 'iskolai csoportok'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='A felhasználó jogosultsági körei: ezek határozzák meg, mit tehet az SZLG+ adminisztrációs felületén. Az alkalmazásoknak nem kerülnek át.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='jogosultsági körök'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='manual_groups',
            field=models.ManyToManyField(blank=True, help_text='A felhasználó iskolai csoportjai (osztály, szakkör stb.): ezeket az alkalmazások az ID tokenben megkapják.', related_name='members', to='api.manualgroup', verbose_name='iskolai csoportok'),
        ),
    ]
