# Generated by Django 5.2.7 on 2026-10-07 00:34

from django.db import migrations, models


def create_global_config(apps, schema_editor):
    GlobalConfig = apps.get_model("api", "GlobalConfig")
    GlobalConfig.objects.get_or_create(pk=1)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_group_naming'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promote_passkey', models.BooleanField(default=True, help_text='Ha be van kapcsolva, a jelszavas bejelentkezés után egy képernyő felajánlja a passkey gyors beállítását azoknak, akiknek még nincs.', verbose_name='passkey ajánlása')),
            ],
            options={
                'verbose_name': 'globális beállítások',
            },
        ),
        migrations.RunPython(create_global_config, migrations.RunPython.noop),
    ]
