# Generated by Django 5.2.7 on 2025-10-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_igazolas_ftv_hianyzas_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTVSyncMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(default='never', max_length=20)),
                ('last_sync_stats', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'FTV Sync Metadata',
                'verbose_name_plural': 'FTV Sync Metadata',
            },
        ),
    ]
