# Generated by Django 5.2.7 on 2026-10-07 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_globalconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagozat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A diák iskolai tagozata.', max_length=100, verbose_name='Tagozat')),
            ],
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'diák profil', 'verbose_name_plural': 'diák profilok'},
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='kezdes_eve',
            field=models.PositiveIntegerField(blank=True, help_text='A diák iskolai tanulmányainak kezdési éve.', null=True, verbose_name='Kezdés éve'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='om_id',
            field=models.CharField(blank=True, help_text='A diák OM azonosítója.', max_length=32, verbose_name='OM azonosító'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='szekcio',
            field=models.CharField(blank=True, help_text='A diák iskolai szekciója.', max_length=10, verbose_name='Szekció'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tagozat',
            field=models.ForeignKey(blank=True, help_text='A diák iskolai tagozata.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tagozat', verbose_name='Tagozat'),
        ),
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together={('user', 'om_id')},
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(fields=('user', 'om_id'), name='unique_user_om_id'),
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_number',
        ),
    ]
