# Generated by Django 5.2.7 on 2025-10-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ftvsyncmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='osztaly',
            name='nem_fogadott_igazolas_tipusok',
            field=models.ManyToManyField(blank=True, related_name='nem_fogado_osztalyok', to='api.igazolastipus'),
        ),
    ]
