# Generated by Django 5.2.7 on 2026-10-07 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tagozat_alter_studentprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentprofile',
            name='unique_user_om_id',
        ),
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together=set(),
        ),
    ]
