# Generated by Django 5.2.7 on 2026-10-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_studentprofile_unique_user_om_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passkey',
            options={'ordering': ['-created_at'], 'verbose_name': 'jelkulcs', 'verbose_name_plural': 'jelkulcsok'},
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='promote_passkey',
            field=models.BooleanField(default=True, help_text='Ha be van kapcsolva, a jelszavas bejelentkezés után egy képernyő felajánlja a jelkulcs gyors beállítását azoknak, akiknek még nincs, illetve azoknak, akik jelszóval léptek be egy olyan eszközön, ahol még nincs jelkulcsuk.', verbose_name='jelkulcs ajánlása'),
        ),
        migrations.AlterField(
            model_name='passkey',
            name='name',
            field=models.CharField(blank=True, default='Jelkulcs', max_length=80, verbose_name='név'),
        ),
    ]
