# Generated by Django 5.2.7 on 2025-11-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_restore_ftvsyncmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A rendszerüzenet címe (maximum 200 karakter)', max_length=200, verbose_name='Cím')),
                ('message', models.TextField(help_text='A rendszerüzenet tartalma (maximum 2000 karakter)', max_length=2000, verbose_name='Üzenet')),
                ('severity', models.CharField(choices=[('info', 'Információ'), ('warning', 'Figyelmeztetés'), ('error', 'Hiba')], default='info', help_text='Az üzenet súlyossága (info/warning/error)', max_length=20, verbose_name='Súlyosság')),
                ('messageType', models.CharField(choices=[('user', 'Felhasználó'), ('developer', 'Fejlesztő'), ('operator', 'Operátor'), ('support', 'Támogatás')], default='user', help_text='Az üzenet célközönsége (user/developer/operator/support)', max_length=20, verbose_name='Üzenet típusa')),
                ('showFrom', models.DateTimeField(help_text='Az üzenet megjelenítésének kezdő időpontja', verbose_name='Megjelenítés kezdete')),
                ('showTo', models.DateTimeField(help_text='Az üzenet megjelenítésének záró időpontja', verbose_name='Megjelenítés vége')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='A rendszerüzenet létrehozásának időpontja', verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='A rendszerüzenet utolsó módosításának időpontja', verbose_name='Módosítva')),
            ],
            options={
                'verbose_name': 'Rendszerüzenet',
                'verbose_name_plural': 'Rendszerüzenetek',
                'ordering': ['-showFrom'],
            },
        ),
    ]
