# Generated by Django 5.2.7 on 2026-10-07 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_tagozat_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagozat',
            options={'ordering': ['name'], 'verbose_name': 'tagozat', 'verbose_name_plural': 'tagozatok'},
        ),
    ]
