# Generated by Django 5.2.7 on 2026-10-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_tagozat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='school_domain',
            field=models.CharField(blank=True, default='@szlgbp.hu', help_text='Az iskola által használt e-mail domain.', max_length=255, null=True, verbose_name='iskolai domain'),
        ),
    ]
