# Generated by Django 5.2.7 on 2025-11-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_tanitasiszunet_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='frontendConfig',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
