# Generated by Django 5.2.7 on 2025-11-06 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_profile_frontendconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PermissionChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('promoted', 'Promoted to Superuser'), ('demoted', 'Demoted from Superuser')], max_length=20)),
                ('previous_value', models.BooleanField()),
                ('new_value', models.BooleanField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_changes_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Change Log',
                'verbose_name_plural': 'Permission Change Logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['user', '-changed_at'], name='api_permiss_user_id_dfa3b3_idx'), models.Index(fields=['changed_by', '-changed_at'], name='api_permiss_changed_d81c62_idx')],
            },
        ),
    ]
