# Generated by Django 5.2.7 on 2025-11-17 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_admin_phase1_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hianyzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mulasztas_datuma', models.DateField(verbose_name='Mulasztás dátuma')),
                ('oraszam', models.IntegerField(verbose_name='Óraszám')),
                ('targy', models.CharField(max_length=100, verbose_name='Tárgy')),
                ('tema', models.CharField(max_length=300, verbose_name='Téma')),
                ('mulasztas_tipusa', models.CharField(max_length=100, verbose_name='Mulasztás típusa')),
                ('igazolt', models.BooleanField(verbose_name='Igazolt')),
                ('tanorai_celu_mulasztas', models.BooleanField(verbose_name='Tanórai célú mulasztás')),
                ('igazolas_tipusa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Igazolás típusa')),
                ('rogzites_datuma', models.DateTimeField(verbose_name='Rögzítés dátuma')),
                ('ok', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ok')),
                ('statusz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Státusz')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Feltöltve')),
                ('tanulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tanuló')),
            ],
            options={
                'verbose_name': 'Hiányzás (eKréta)',
                'verbose_name_plural': 'Hiányzások (eKréta)',
                'ordering': ['-mulasztas_datuma', 'oraszam'],
                'indexes': [models.Index(fields=['tanulo', '-mulasztas_datuma'], name='api_hianyza_tanulo__8867d6_idx')],
            },
        ),
    ]
