# Generated by Django 5.2.7 on 2025-11-17 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_hianyzas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hianyzas',
            name='tanulo',
        ),
        migrations.AddField(
            model_name='mulasztas',
            name='mulasztas_ok',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Mulasztás oka'),
        ),
        migrations.AddField(
            model_name='mulasztas',
            name='mulasztas_statusz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mulasztás státusz'),
        ),
        migrations.AddField(
            model_name='mulasztas',
            name='tanorai_celu_mulasztas',
            field=models.BooleanField(default=False, verbose_name='Tanórai célú mulasztás'),
        ),
        migrations.AddField(
            model_name='mulasztas',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Feltöltve (eKréta)'),
        ),
        migrations.AddField(
            model_name='mulasztas',
            name='uploaded_by_student',
            field=models.ForeignKey(blank=True, help_text='Ha diák töltötte fel eKrétából (EXPERIMENTAL)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_mulasztasok', to=settings.AUTH_USER_MODEL, verbose_name='Feltöltő diák'),
        ),
        migrations.AddIndex(
            model_name='mulasztas',
            index=models.Index(fields=['uploaded_by_student', '-datum'], name='api_mulaszt_uploade_5d9074_idx'),
        ),
        migrations.DeleteModel(
            name='Hianyzas',
        ),
    ]
