# Generated by Django 5.2.7 on 2025-11-17 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_hianyzas_tanulo_mulasztas_mulasztas_ok_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='igazolas',
            name='academic_year',
            field=models.CharField(blank=True, help_text='Pl. 2024/2025', max_length=20, null=True, verbose_name='Tanév'),
        ),
        migrations.AddField(
            model_name='igazolas',
            name='archived',
            field=models.BooleanField(default=False, help_text='Az igazolás archivált státuszban van', verbose_name='Archivált'),
        ),
        migrations.AddField(
            model_name='igazolas',
            name='created_by_group_leader',
            field=models.ForeignKey(blank=True, help_text='A csoportos igazolást létrehozó felhasználó', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_group_igazolasok', to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta (csoport vezető)'),
        ),
        migrations.AddField(
            model_name='igazolas',
            name='group_id',
            field=models.UUIDField(blank=True, help_text='UUID amely összeköti a csoportos igazolásokat', null=True, verbose_name='Csoport azonosító'),
        ),
        migrations.AddField(
            model_name='igazolas',
            name='group_member_count',
            field=models.IntegerField(default=1, verbose_name='Csoport létszám'),
        ),
        migrations.AddField(
            model_name='igazolas',
            name='is_group_leader',
            field=models.BooleanField(default=False, help_text='Az igazolást létrehozó diák', verbose_name='Csoport vezető'),
        ),
        migrations.AddField(
            model_name='igazolastipus',
            name='requires_studios',
            field=models.BooleanField(default=False, help_text='Csak stúdiós diákok használhatják ezt az igazolás típust', verbose_name='Stúdiós szükséges'),
        ),
        migrations.AddField(
            model_name='igazolastipus',
            name='supports_group_absence',
            field=models.BooleanField(default=False, help_text='Lehetővé teszi több diák párhuzamos igazolását ugyanarra az eseményre', verbose_name='Csoportos hiányzást támogat'),
        ),
        migrations.AddField(
            model_name='mulasztas',
            name='matched_igazolas',
            field=models.ForeignKey(blank=True, help_text='Az igazolás ami fedezi ezt a mulasztást', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_mulasztasok', to='api.igazolas', verbose_name='Párosított igazolás'),
        ),
        migrations.AddField(
            model_name='osztaly',
            name='academic_year',
            field=models.CharField(blank=True, help_text='Pl. 2024/2025', max_length=20, null=True, verbose_name='Tanév'),
        ),
        migrations.AddField(
            model_name='osztaly',
            name='archive_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archiválás dátuma'),
        ),
        migrations.AddField(
            model_name='osztaly',
            name='archived',
            field=models.BooleanField(default=False, help_text='Az osztály archivált státuszban van', verbose_name='Archivált'),
        ),
        migrations.AddField(
            model_name='osztaly',
            name='enabled_periods',
            field=models.JSONField(blank=True, default=list, help_text='Lista az engedélyezett tanórai időszakokról (pl. [1,2,3,4,5,6,7])', verbose_name='Engedélyezett órák'),
        ),
        migrations.AddField(
            model_name='profile',
            name='academic_year',
            field=models.CharField(blank=True, help_text='Pl. 2024/2025', max_length=20, null=True, verbose_name='Tanév'),
        ),
        migrations.AddField(
            model_name='profile',
            name='archive_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archiválás dátuma'),
        ),
        migrations.AddField(
            model_name='profile',
            name='archived',
            field=models.BooleanField(default=False, help_text='A profil archivált státuszban van', verbose_name='Archivált'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_studios',
            field=models.BooleanField(default=False, help_text='A diák stúdiós programban vesz részt', verbose_name='Stúdiós'),
        ),
    ]
