# Generated by Django 5.2.7 on 2025-11-17 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_igazolas_academic_year_igazolas_archived_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_path', models.CharField(max_length=500, verbose_name='Endpoint Path')),
                ('http_method', models.CharField(max_length=10, verbose_name='HTTP Method')),
                ('avg_response_ms', models.FloatField(verbose_name='Average Response Time (ms)')),
                ('request_count', models.IntegerField(default=0, verbose_name='Request Count')),
                ('error_count', models.IntegerField(default=0, verbose_name='Error Count')),
                ('p95_response_ms', models.FloatField(blank=True, null=True, verbose_name='95th Percentile Response Time (ms)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Recorded At')),
                ('detailed_metrics', models.JSONField(blank=True, default=dict, help_text='Additional metrics data in JSON format', verbose_name='Detailed Metrics')),
            ],
            options={
                'verbose_name': 'API Metrika',
                'verbose_name_plural': 'API Metrikák',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['endpoint_path', 'http_method'], name='api_apimetr_endpoin_dc6cb5_idx'), models.Index(fields=['-recorded_at'], name='api_apimetr_recorde_534e87_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImpersonationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Kezdés Időpontja')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Befejezés Időpontja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('actions_performed', models.JSONField(blank=True, default=list, help_text='List of actions performed during impersonation', verbose_name='Elvégzett Műveletek')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Cím')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='User Agent')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_sessions_as_admin', to=settings.AUTH_USER_MODEL, verbose_name='Admin Felhasználó')),
                ('impersonated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_sessions_as_target', to=settings.AUTH_USER_MODEL, verbose_name='Megszemélyesített Felhasználó')),
            ],
            options={
                'verbose_name': 'Impersonation Log',
                'verbose_name_plural': 'Impersonation Logs',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['admin_user', '-start_time'], name='api_imperso_admin_u_e6fe31_idx'), models.Index(fields=['is_active'], name='api_imperso_is_acti_7fdc19_idx')],
            },
        ),
    ]
