# Generated by Django 5.2.7 on 2025-11-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_impersonation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='igazolastipus',
            options={'ordering': ['category', 'display_order', 'nev'], 'verbose_name': 'Igazolás Típus', 'verbose_name_plural': 'Igazolás Típusok'},
        ),
        migrations.AddField(
            model_name='igazolas',
            name='sub_form_data',
            field=models.JSONField(blank=True, help_text='Típus-specifikus további adatok JSON formátumban', null=True, verbose_name='Alkérdőív adatok'),
        ),
        migrations.AddField(
            model_name='igazolastipus',
            name='category',
            field=models.CharField(choices=[('egeszsegugy', 'Egészségügyi'), ('verseny', 'Verseny'), ('kulturalis', 'Kulturális/Művészeti'), ('kozlekedes', 'Közlekedés'), ('tanulmanyi', 'Tanulmányi'), ('csaladi', 'Családi'), ('egyeb', 'Egyéb')], default='egyeb', max_length=50, verbose_name='Kategória'),
        ),
        migrations.AddField(
            model_name='igazolastipus',
            name='category_emoji',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Kategória emoji'),
        ),
        migrations.AddField(
            model_name='igazolastipus',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Kategórián belüli sorrend (alacsonyabb = előrébb)', verbose_name='Megjelenítési sorrend'),
        ),
        migrations.AddField(
            model_name='igazolastipus',
            name='has_sub_form',
            field=models.BooleanField(default=False, help_text='A típus további adatokat kér (pl. verseny részletek)', verbose_name='Van alkérdőív'),
        ),
        migrations.AddField(
            model_name='igazolastipus',
            name='sub_form_schema',
            field=models.JSONField(blank=True, help_text='JSON séma a további mezőkhöz', null=True, verbose_name='Alkérdőív séma'),
        ),
    ]
