# Generated by Django 5.2.7 on 2026-07-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_passkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='igazolas',
            name='image',
            field=models.ImageField(blank=True, help_text='Igazoláshoz csatolt, tömörített kép', null=True, upload_to='igazolas_images/', verbose_name='Kép'),
        ),
    ]
