# Generated by Django 5.2.7 on 2026-07-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_igazolas_reszletes_idopontok'),
    ]

    operations = [
        migrations.AddField(
            model_name='igazolas',
            name='undoed',
            field=models.BooleanField(default=False, help_text='A diák visszavonta az igazolást', verbose_name='Visszavont'),
        ),
    ]
