# Generated by Django 5.2.7 on 2026-08-12 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_mulasztas_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A bejegyzés címe (maximum 200 karakter)', max_length=200, verbose_name='Cím')),
                ('content', models.TextField(help_text='Markdown formázott tartalom (képek is beágyazhatók)', verbose_name='Tartalom')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('published_at', models.DateTimeField(blank=True, help_text='Ha üres, a bejegyzés vázlat és senkinek sem jelenik meg', null=True, verbose_name='Közzététel időpontja')),
                ('show_to_students', models.BooleanField(default=True, verbose_name='Diákoknak mutatva')),
                ('show_to_teachers', models.BooleanField(default=True, verbose_name='Tanároknak mutatva')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_change_notes', to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
                ('target_classes', models.ManyToManyField(blank=True, help_text='Ha üres, minden osztály látja (a fenti kapcsolóknak megfelelően)', related_name='change_notes', to='api.osztaly', verbose_name='Célosztályok')),
            ],
            options={
                'verbose_name': 'Változás bejegyzés',
                'verbose_name_plural': 'Változás bejegyzések',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeNoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='change_note_images/', verbose_name='Kép')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Feltöltve')),
                ('change_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.changenote', verbose_name='Változás bejegyzés')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Feltöltötte')),
            ],
            options={
                'verbose_name': 'Változás bejegyzés kép',
                'verbose_name_plural': 'Változás bejegyzés képek',
            },
        ),
    ]
