# Generated by Django 5.2.7 on 2026-08-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_changenote_changenoteimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igazolas',
            name='allapot',
            field=models.CharField(choices=[('Függőben', 'Függőben'), ('Elfogadva', 'Elfogadva'), ('Elutasítva', 'Elutasítva'), ('Hiánypótlásra visszaküldve', 'Hiánypótlásra visszaküldve')], default='Függőben', max_length=50),
        ),
    ]
