# Generated by Django 5.2.7 on 2026-09-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_igazolas_allapot'),
    ]

    operations = [
        migrations.AddField(
            model_name='igazolas',
            name='ftv_forgatas_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='igazolas',
            name='ftv_forgatas_veg_datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='igazolas',
            name='ftv_korrigalhato',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='igazolas',
            name='ftv_tobbnapos',
            field=models.BooleanField(default=False),
        ),
    ]
