"""
Django settings for igazolasbackend project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

def config(key, default=None, cast=None):
    """Simple config function to read environment variables"""
    value = os.environ.get(key, default)
    if value is None:
        raise ValueError(f"Environment variable '{key}' not found and no default provided")
    if cast:
        try:
            if cast == bool:
                # Handle boolean values
                return value.lower() in ('true', '1', 'yes', 'on')
            return cast(value)
        except (ValueError, TypeError) as e:
            raise ValueError(f"Failed to cast '{key}' value '{value}' to {cast.__name__}: {e}")
    return value

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=lambda v: [s.strip() for s in v.split(',') if s.strip()])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'igazolasbackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'igazolasbackend' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'igazolasbackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 20,  # Wait up to 20 seconds for locks to clear
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Budapest'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '__szlg/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads – served exclusively through the protected API endpoint)
MEDIA_URL = '__szlg/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Image upload configuration
IMAGE_MAX_UPLOAD_SIZE_MB = config('IMAGE_MAX_UPLOAD_SIZE_MB', default=10, cast=int)   # raw upload limit
IMAGE_MAX_DIMENSION = config('IMAGE_MAX_DIMENSION', default=1920, cast=int)           # longest edge in px
IMAGE_QUALITY = config('IMAGE_QUALITY', default=85, cast=int)                         # JPEG quality

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# JWT Configuration
JWT_SECRET_KEY = config('JWT_SECRET_KEY', default=SECRET_KEY)  # Use separate key or fallback to SECRET_KEY
JWT_ALGORITHM = config('JWT_ALGORITHM', default='HS256')
JWT_EXPIRATION_DELTA = config('JWT_EXPIRATION_DELTA', default=86400, cast=int)  # 24 hours in seconds

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=True, cast=bool)  # In production, specify allowed origins
CORS_ALLOW_CREDENTIALS = config('CORS_ALLOW_CREDENTIALS', default=True, cast=bool)
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='szlghonlap.ftv@gmail.com')

# OTP Configuration
OTP_EXPIRY_MINUTES = config('OTP_EXPIRY_MINUTES', default=15, cast=int)
RESET_TOKEN_EXPIRY_MINUTES = config('RESET_TOKEN_EXPIRY_MINUTES', default=10, cast=int)

# BKK API Configuration
BKK_TOKEN = config('BKK_TOKEN', default='')

# WebAuthn / Passkey Configuration
WEBAUTHN_RP_ID = config('WEBAUTHN_RP_ID', default='localhost')
WEBAUTHN_RP_NAME = config('WEBAUTHN_RP_NAME', default='Igazoláskezelő')
WEBAUTHN_ORIGINS = config(
    'WEBAUTHN_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000,https://igazolas.szlg.info',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()],
)

# FTV External API Configuration
FTV_EXTERNAL_ACCESS_TOKEN = config('FTV_EXTERNAL_ACCESS_TOKEN', default='')

# Cache Configuration
# Using LocMemCache for development - consider Redis for production with multiple servers
# Note: LocMemCache is cleared on server restart. Use Redis or database cache for persistence.
CACHES = {
    'default': {
        # Option 1: In-memory cache (fast but cleared on restart)
        # 'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        # 'LOCATION': 'unique-snowflake',
        
        # Option 2: Database cache (persistent across restarts)
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
        'OPTIONS': {
            'MAX_ENTRIES': 10000,  # Maximum number of cache entries
        },
        
        # Option 3: Redis cache (best for production, requires redis-py package)
        # 'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        # 'LOCATION': 'redis://127.0.0.1:6379/1',
    }
}

